/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tquery.gui;

import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.stage.FileChooser;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import tquery.TweetsSpider;
import tquery.utils.CSVTweetsWriter;

/**
 *
 * @author MHJ
 */
public class FrmQuery extends javax.swing.JFrame {

    /**
     * Creates new form FrmQuery
     */
    
    private TweetsSpider spider;
    
    private Thread spiderWorker;
    
    public FrmQuery() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtAllWords = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtExact = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtAnyWords = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNoneWords = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtHashTags = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cmbLangs = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtFromAccount = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtToAccount = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtMentioning = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtPlace = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtSince = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtUntil = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        ckPositive = new javax.swing.JCheckBox();
        ckNegative = new javax.swing.JCheckBox();
        ckQuestions = new javax.swing.JCheckBox();
        ckRetweets = new javax.swing.JCheckBox();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        opCSV = new javax.swing.JRadioButton();
        opJSON = new javax.swing.JRadioButton();
        opSQLIte = new javax.swing.JRadioButton();
        txtFilePath = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        btnBrwose = new javax.swing.JButton();
        btnStart = new javax.swing.JButton();
        btnStop = new javax.swing.JButton();
        lblMsgs = new javax.swing.JLabel();
        lblTweetsLog = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("tQuery");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Advanced Search"));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Words");

        jLabel2.setText("All of these words");

        jLabel3.setText("This exact phrase");

        jLabel4.setText("Any of these words");

        jLabel5.setText("None of these words");

        jLabel6.setText("These hashtags");

        jLabel7.setText("Written in");

        cmbLangs.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Any Language", "Amharic (አማርኛ)", "Arabic (العربية)", "Armenian (հայերեն)", "Bengali (বাংলা)", "Bosnian (bosanski)", "Bulgarian (български)", "Burmese (ဗမာ)", "<option value=\"ckb\">Central Kurdish (کوردیی ناوەندی)", "Chinese (中文)", "Croatian (hrvatski)", "Danish (dansk)", "Divehi (Divehi)", "Dutch (Nederlands)", "English (English)", "Estonian (eesti)", "Finnish (suomi)", "French (français)", "Georgian (ქართული)", "German (Deutsch)", "Greek (Ελληνικά)", "Gujarati (ગુજરાતી)", "Hebrew (עברית)", "Hindi (हिन्दी)", "Hungarian (magyar)", "Icelandic (íslenska)", "Indonesian (Bahasa Indonesia)", "Italian (italiano)", "Japanese (日本語)", "Kannada (ಕನ್ನಡ)", "Khmer (ខ្មែរ)", "Korean (한국어)", "Lao (ລາວ)", "Latvian (latviešu)", "Lithuanian (lietuvių)", "Malayalam (മലയാളം)", "Marathi (मराठी)", "Nepali (नेपाली)", "Norwegian (norsk)", "Oriya (ଓଡ଼ିଆ)", "Pashto (پښتو)", "Persian (فارسی)", "Polish (polski)", "Portuguese (português)", "Punjabi (ਪੰਜਾਬੀ)", "Romanian (română)", "Russian (русский)", "Serbian (српски)", "Sindhi (سنڌي)", "Sinhala (සිංහල)", "Slovak (slovenčina)", "Slovenian (slovenščina)", "Spanish (español)", "Swedish (svenska)", "Tagalog (Tagalog)", "Tamil (தமிழ்)", "Telugu (తెలుగు)", "Thai (ไทย)", "Tibetan (བོད་སྐད་)", "Turkish (Türkçe)", "Urdu (اردو)", "Uyghur (ئۇيغۇرچە)", "Vietnamese (Tiếng Việt)" }));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("People");

        jLabel9.setText("From these accounts");

        jLabel10.setText("To these accounts");

        jLabel11.setText("Mentioning these accounts");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Places");

        jLabel13.setText("Near this place");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Dates");

        jLabel15.setText("From this date ");

        jLabel16.setText("to");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("Other");

        ckPositive.setText("Positive :)");

        ckNegative.setText("Negative :(");

        ckQuestions.setText("Question ?");

        ckRetweets.setText("Include retweets");

        jLabel22.setText("yyyy-mm-dd");

        jLabel23.setText("yyyy-mm-dd");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel13)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel8)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel12))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel14))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabel15)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAllWords)
                            .addComponent(txtExact)
                            .addComponent(txtAnyWords)
                            .addComponent(txtNoneWords)
                            .addComponent(txtHashTags)
                            .addComponent(cmbLangs, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtFromAccount)
                            .addComponent(txtToAccount)
                            .addComponent(txtMentioning)
                            .addComponent(txtPlace)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtSince, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(66, 66, 66)
                                        .addComponent(jLabel16))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(ckPositive)
                                        .addGap(27, 27, 27)
                                        .addComponent(ckNegative)
                                        .addGap(18, 18, 18)
                                        .addComponent(ckQuestions)
                                        .addGap(4, 4, 4)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 40, Short.MAX_VALUE)
                                        .addComponent(txtUntil, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(ckRetweets)
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel17)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(241, 241, 241)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel23)
                .addGap(67, 67, 67))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtAllWords, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtExact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtAnyWords, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtNoneWords, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtHashTags, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmbLangs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtFromAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtToAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(txtMentioning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtPlace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSince, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16)
                        .addComponent(txtUntil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckPositive)
                    .addComponent(ckNegative)
                    .addComponent(ckQuestions)
                    .addComponent(ckRetweets))
                .addGap(23, 23, 23))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Save options"));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("Output format");

        buttonGroup1.add(opCSV);
        opCSV.setText("CSV");

        buttonGroup1.add(opJSON);
        opJSON.setText("JSON");

        buttonGroup1.add(opSQLIte);
        opSQLIte.setText("SQLite");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setText("File path");

        btnBrwose.setText("...");
        btnBrwose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrwoseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(101, 101, 101)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(opCSV)
                                .addGap(18, 18, 18)
                                .addComponent(opJSON)
                                .addGap(18, 18, 18)
                                .addComponent(opSQLIte))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtFilePath)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBrwose)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addGap(4, 4, 4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opCSV)
                    .addComponent(opJSON)
                    .addComponent(opSQLIte))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel19))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFilePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBrwose))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnStart.setText("Start");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        btnStop.setText("Stop");
        btnStop.setEnabled(false);
        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });

        lblMsgs.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblMsgs.setText("Click start to start scraping tweets..");

        lblTweetsLog.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTweetsLog.setText("0 tweet(s) scraped");

        jLabel20.setText("This scraper has been developed by: Mohammed Jabreel, PhD reaseacher @ iTAKA group, URV, Tarragona Spain");

        jLabel21.setText("Email: mhjabreel@gmail.com");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnStart)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnStop))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblMsgs)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblTweetsLog))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel20))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStart)
                    .addComponent(btnStop))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMsgs)
                    .addComponent(lblTweetsLog))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel21)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        
        String [] langs = new String[] {
              "am",
              "ar",
              "hy",
              "bn",
              "bs",
              "bg",
              "my",
              "ckb",
              "zh",
              "hr",
              "da",
              "dv",
              "nl",
              "en",
              "et",
              "fi",
              "fr",
              "ka",
              "de",
              "el",
              "gu",
              "he",
              "hi",
              "hu",
              "is",
              "id",
              "it",
              "ja",
              "kn",
              "km",
              "ko",
              "lo",
              "lv",
              "lt",
              "ml",
              "mr",
              "ne",
              "no",
              "or",
              "ps",
              "fa",
              "pl",
              "pt",
              "pa",
              "ro",
              "ru",
              "sr",
              "sd",
              "si",
              "sk",
              "sl",
              "es",
              "sv",
              "tl",
              "ta",
              "te",
              "th",
              "bo",
              "tr",
              "ur",
              "ug",
              "vi"            
        };
        
        btnStart.setEnabled(false);
        btnStop.setEnabled(true);
        
        
        
        List<String> params = new ArrayList<>();
        
        //a, b c "d, e" t OR y -z #rr lang:ar from:m to:n @A near:"k" within:15mi since:2015-10-28 until:2015-10-29 :) :( ? include:retweets
        
        if(!txtAllWords.getText().isEmpty()) {
            params.add(txtAllWords.getText().trim());
        }
        
        if(!txtExact.getText().isEmpty()) {
            params.add(String.format("\"%s\"", txtExact.getText().trim()));
        }
        
        if(!txtAnyWords.getText().isEmpty()) {
            params.add(txtAnyWords.getText().trim().replace(" ", " OR "));
        }
        
        if(!txtNoneWords.getText().isEmpty()) {
            params.add("-" +txtNoneWords.getText().trim().replace(" ", " -"));
        }
        
        if(!txtHashTags.getText().isEmpty()) {
            params.add("#" + txtHashTags.getText().trim().replace(" ", " OR #"));
        } 
        
        if(cmbLangs.getSelectedIndex() > 0) {
            params.add(String.format("lang:%s", langs[cmbLangs.getSelectedIndex() - 1]));
        }
        
        if(!txtFromAccount.getText().isEmpty()) {
            params.add("from:" + txtFromAccount.getText().trim().replace(" ", " OR from:"));
        }
        
        if(!txtToAccount.getText().isEmpty()) {
            params.add("to:" + txtToAccount.getText().trim().replace(" ", " OR to:"));
        }  
        
        if(!txtMentioning.getText().isEmpty()) {
            params.add("@" + txtMentioning.getText().trim().replace(" ", " OR @"));
        }        
        
        if(!txtPlace.getText().isEmpty()) {
            params.add(String.format("near:\"%s\" within:15mi", txtPlace.getText().trim())); 
        }
        
        if(!txtSince.getText().isEmpty()) {
            params.add("since:" + txtSince.getText().trim());
        }    
        
        if(!txtUntil.getText().isEmpty()) {
            params.add("until:" + txtUntil.getText().trim());
        }    
        
        if(ckPositive.isSelected()) {
            params.add(":)");
        }
  
        if(ckNegative.isSelected()) {
            params.add(":(");
        }
        
        if(ckQuestions.isSelected()) {
            params.add("?");
        }        
        
        if(ckRetweets.isSelected()) {
            params.add("include:retweets");
        } 
        
        String query = String.join(" ", params);
        
        System.out.println(query);
        
        spiderWorker = new Thread(new Runnable() {

            @Override
            public void run() {
                if(opCSV.isSelected()) {
                    spider = new TweetsSpider(new CSVTweetsWriter(txtFilePath.getText()), lblTweetsLog);
                    spider.crawlTweets(query);
                    btnStart.setEnabled(true);
                    btnStop.setEnabled(false);                    
                }                
            }
        });
        
        spiderWorker.start();
               
        
    }//GEN-LAST:event_btnStartActionPerformed

    private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopActionPerformed
        this.spider.setNeedToStop(true);
        try {
            spiderWorker.join();
        } catch (InterruptedException ex) {
            Logger.getLogger(FrmQuery.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.btnStart.setEnabled(true);
        this.btnStop.setEnabled(false);
    }//GEN-LAST:event_btnStopActionPerformed

    private void btnBrwoseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrwoseActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Specify a file to save");
        fileChooser.setFileFilter(new FileNameExtensionFilter("csv file","csv"));
        int userSelection = fileChooser.showSaveDialog(this);
        if (userSelection == JFileChooser.APPROVE_OPTION) {
            txtFilePath.setText(fileChooser.getSelectedFile().getAbsolutePath());
        }        
        
    }//GEN-LAST:event_btnBrwoseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmQuery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmQuery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmQuery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmQuery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmQuery().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrwose;
    private javax.swing.JButton btnStart;
    private javax.swing.JButton btnStop;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox ckNegative;
    private javax.swing.JCheckBox ckPositive;
    private javax.swing.JCheckBox ckQuestions;
    private javax.swing.JCheckBox ckRetweets;
    private javax.swing.JComboBox cmbLangs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblMsgs;
    private javax.swing.JLabel lblTweetsLog;
    private javax.swing.JRadioButton opCSV;
    private javax.swing.JRadioButton opJSON;
    private javax.swing.JRadioButton opSQLIte;
    private javax.swing.JTextField txtAllWords;
    private javax.swing.JTextField txtAnyWords;
    private javax.swing.JTextField txtExact;
    private javax.swing.JTextField txtFilePath;
    private javax.swing.JTextField txtFromAccount;
    private javax.swing.JTextField txtHashTags;
    private javax.swing.JTextField txtMentioning;
    private javax.swing.JTextField txtNoneWords;
    private javax.swing.JTextField txtPlace;
    private javax.swing.JTextField txtSince;
    private javax.swing.JTextField txtToAccount;
    private javax.swing.JTextField txtUntil;
    // End of variables declaration//GEN-END:variables
}
